version: '3'

vars:
  BINARY_NAME: go-qq-bot
  BUILD_DIR: ./bin
  MAIN_PATH: ./main.go

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  dev:
    desc: Run development server with hot reload (requires air)
    cmds:
      - go tool air
    silent: false

  dev:simple:
    desc: Run development server without hot reload
    cmds:
      - go run {{.MAIN_PATH}}
    silent: false

  build:
    desc: Build binary for current platform
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.MAIN_PATH}}
    silent: false

  build:all:
    desc: Build binaries for multiple platforms
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - GOOS=linux GOARCH=amd64 go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-linux-amd64 {{.MAIN_PATH}}
      - GOOS=darwin GOARCH=amd64 go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-darwin-amd64 {{.MAIN_PATH}}
      - GOOS=darwin GOARCH=arm64 go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-darwin-arm64 {{.MAIN_PATH}}
      - GOOS=windows GOARCH=amd64 go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}}-windows-amd64.exe {{.MAIN_PATH}}
    silent: false

  run:
    desc: Run the built binary
    deps: [build]
    cmds:
      - '{{.BUILD_DIR}}/{{.BINARY_NAME}}'
    silent: false

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...
    silent: false

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
    silent: false

  lint:
    desc: Run linter (requires golangci-lint)
    cmds:
      - golangci-lint run
    silent: false

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...
    silent: false

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...
    silent: false

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy
    silent: false

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -f coverage.out coverage.html
    silent: false

  install:deps:
    desc: Install development dependencies
    cmds:
      - go get -tool github.com/air-verse/air@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    silent: false

  check:
    desc: Run all checks (fmt, vet, lint, test)
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test
    silent: false
